#!/bin/bash

NAME="djangochannels"
DIR=/home/ubuntu/Channels-testing
USER=ubuntu
WORKERS=3
BIND=unix:/home/ubuntu/run/gunicorn.sock
DJANGO_SETTINGS_MODULE=djangochannels.settings
DJANGO_WSGI_MODULE=djangochannels.wsgi
LOG_LEVEL=error

cd $DIR
source ../shell/bin/activate

export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DIR:$PYTHONPATH
exec gunicorn ${DJANGO_WSGI_MODULE}:application --name $NAME --workers $WORKERS --user=$USER --bind=$BIND 